export const REACT_APP_CRYPTOCOMPARE_URL =
    process.env.REACT_APP_CRYPTOCOMPARE_URL;

export const REACT_APP_YOUTUBE_APIKEY =
    process.env.REACT_APP_YOUTUBE_APIKEY;

export const REACT_APP_YOUTUBE_BASE_URL =
    process.env.REACT_APP_YOUTUBE_BASE_URL; 

